rock = [
    'Acid_rock',
    'Adult_contemporary_music',
    'Adult_alternative',
    'Afro-punk',
    'Afro_rock',
    'Alternative_country',
    'Alternative_dance',
    'Alternative_hip_hop',
    'Alternative_metal',
    'Alternative_rock',
    'Americana_music',
    'Anarcho-punk',
    'Anti_folk',
    'Anatolian_rock',
    'Arena_rock',
    'Art_punk',
    'Art_rock',
    'Baggy',
    'Beach_music',
    'Beat_music',
    'Bent_edge',
    'Bigbit',
    'BisRock',
    'Blues_rock',
    'Boogie_rock',
    'British_folk_rock',
    'Britpop',
    'Canterbury_sound',
    'Cello_rock',
    'Chillwave',
    'Celtic_punk',
    'Celtic_rock',
    'Chicano_rock',
    'Cock_rock',
    'Coldwave',
    'College_rock',
    'Comedy_rock',
    'Country_rock',
    'Cowpunk',
    'Crossover_thrash',
    'Crunkcore',
    'Crust_punk',
    'Cybergrind',
    'Dance-punk',
    'Dance-rock',
    'Dark_cabaret',
    'Darkwave',
    'Death_n_roll',
    'Deathrock',
    'Desert_blues',
    'Digital_hardcore',
    'Dolewave',
    'Dream_pop',
    'Dunedin_sound',
    'Dungeon_synth',
    'Electroclash',
    'Electropunk',
    'Electronicore',
    'Electronic_rock',
    'Emo',
    'Emo_pop',
    'Emo_revival',
    'Emo_rap',
    'Ethereal_wave',
    'Experimental_rock',
    'Flamenco_rock',
    'Folk_punk',
    'Folk_rock',
    'Funk_rock',
    'Garage_rock',
    'Geek_rock',
    'Glam_punk',
    'Glam_rock',
    'Gothic_rock',
    'Grebo',
    'Grindie',
    'Groove_metal',
    'Group_Sounds',
    'Grunge',
    'Gypsy_punk',
    'Hard_rock',
    'Hardcore_punk',
    'Heartland_rock',
    'Horror_punk',
    'Hyperpop',
    'Indie_folk',
    'Indie_pop',
    'Indie_rock',
    'Indietronica',
    'Industrial_rock',
    'Instrumental_rock',
    'Italian_occult_psychedelia',
    'Jazz_fusion',
    'Jangle_pop',
    'Jersey_Shore_sound',
    'Kindie_rock',
    'Krautrock',
    'Kawaii_metal',
    'Latin_alternative',
    'Latin_metal',
    'Latin_rock',
    'Lovers_rock',
    'Madchester',
    'Manila_Sound',
    'Mathcore',
    'Math_rock',
    'Medieval_folk_rock',
    'Medieval_metal',
    'Melodic_death_metal',
    'Melodic_hardcore',
    'Melodic_metalcore',
    'Midwest_emo',
    'Minneapolis_sound',
    'Metalcore',
    'Metalstep',
    'Mod_revival',
    'Modern_Rock',
    'Nardcore',
    'Neoclassical_dark_wave',
    'Neoclassical_metal',
    'Neon_pop',
    'Neo-prog',
    'Neo-psychedelia',
    'New_rave',
    'New_wave',
    'New_wave_of_new_wave',
    'New_Weird_America',
    'Nintendocore',
    'Noise_pop',
    'Noise_rock',
    'No_wave',
    'Nu_gaze',
    'Nu_metal',
    'Nu_metalcore',
    'Occult_rock',
    'Oi',
    'Ostrock',
    'Outlaw_country',
    'Pagan_metal',
    'Pagan_rock',
    'Paisley_Underground',
    'Peace_punk',
    'Pinoy_rock',
    'Pirate_metal',
    'Pop_metal',
    'Pop_punk',
    'Pop_rock',
    'Pornogrind',
    'Post-britpop',
    'Post-grunge',
    'Post-hardcore',
    'Post-metal',
    'Post-punk',
    'Post-punk_revival',
    'Post-rock',
    'Power_ballad',
    'Power_pop',
    'Power_metal',
    'Powerviolence',
    'Progressive_metal',
    'Progressive_metalcore',
    'Progressive_pop',
    'Progressive_rock',
    'Progressive_soul',
    'Proto-prog',
    'Protopunk',
    'Psychedelic_folk',
    'Psychedelic_funk',
    'Psychedelic_pop',
    'Psychedelic_rock',
    'Psychedelic_soul',
    'Psychobilly',
    'Pub_rock',
    'Punk_blues',
    'Punk_jazz',
    'Punk_rap',
    'Punk_rock',
    'Punk_pathetique',
    'Queercore',
    'Raga_rock',
    'Rapcore',
    'Rap_metal',
    'Rap_rock',
    'Reggae_rock',
    'Red_dirt',
    'Riot_grrrl',
    'Rock_Against_Communism',
    'Rock_and_roll',
    'Rocksteady',
    'Rockabilly',
    'Rock_music',
    'Rock_in_Opposition',
    'Roots_rock',
    'Sadcore',
    'Samba_rock',
    'Screamo',
    'Shaman_punk',
    'Shoegaze',
    'Shock_rock',
    'Ska_punk',
    'Skate_punk',
    'Slacker_rock',
    'Slowcore',
    'Sludge_metal',
    'Soft_grunge',
    'Soft_rock',
    'Southern_rock',
    'Space_rock',
    'Speed_metal',
    'Straight_edge',
    'Stoner_rock',
    'Street_punk',
    'Sufi_rock',
    'Sunshine_pop',
    'Surf_music',
    'Swamp_pop',
    'Swamp_rock',
    'Swedish_death_metal',
    'Symphonic_black_metal',
    'Symphonic_metal',
    'Synth-metal',
    'Synth_Pop',
    'Synth-punk',
    'Taqwacore',
    'Technical_death_metal',
    'Teutonic_thrash_metal',
    'Thrashcore',
    'Thrash_metal',
    'Time_Lord_rock',
    'Trallpunk',
    'Trap_metal',
    'Trønder_rock',
    'Tropicália',
    'Tropical_rock',
    'Tulsa_Sound',
    'UK_82',
    'Unblack_metal',
    'VIA',
    'Viking_metal',
    'Viking_rock',
    'Visual_kei',
    'Wagnerian_rock',
    'War_metal',
    'Wizard_rock',
    'Wonky_pop',
    'Worldbeat',
    'Yacht_rock',
    'Youth_crew',
    'Zeuhl']

pop = [
    'Adult contemporary music',
'Akishibu-kei',
'Arabic pop music',
'Art pop',
'Assyrian folk-pop music',
'Avant-pop',
'Beat music',
'Bhangra (music)',
'Bitpop',
'Boy band',
'Bubblegum music',
'Čalgija',
'California sound'
'Cantopop',
'Chalga',
'Chillwave',
'Christian pop music',
'Country pop',
'Coupé-décalé',
'Cowboy pop',
'Cringe pop',
'Dance-pop',
'Dancehall pop',
'Disco polo',
'Doo-wop',
'Electropop',
'Estrada'
'Eurodance',
'Europop',
'Experimental pop',
'Folk-pop',
'Freestyle music',
'Group sounds',
'Hokkien pop',
'Hong Kong English pop',
'Hyperpop',
'Hypnagogic pop',
'Indie pop',
'Italo dance',
'K-pop',
'Kayōkyoku',
'Lao pop',
'Laïko',
'Latin pop',
'Mandopop',
'Manele',
'Nashville sound',
'Nederbeat',
'Nordik beat',
'Operatic pop',
'Orchestral pop',
'Orthodox pop music',
'Pinoy pop',
'Pop metal',
'Pop rap',
'Pop rock',
'Pop-punk',
'Power pop',
'Progressive pop',
'Psychedelic music',
'Psychedelic pop',
'Q-pop',
'Quiet storm',
'Russian pop',
'Sad pop',
'Shibuya-kei',
'Shidaiqu',
'Skiladiko',
'Sophisti-pop',
'Space age pop',
'Sunshine pop',
'Swamp pop',
'Symphonic pop',
'Synth-pop',
'Tallava',
'Teen pop',
'Thai pop music',
'Traditional pop',
'Tropical rock',
'Tropipop',
'Twee pop',
'Vispop',
'Wong shadow',
'Wonky pop',
'Xinyao',
'Zhongguo feng'
]